---
# Create containerized qemu instances for K8s cluster
# This playbook also creates veth interfaces to connect SRL leaf at ethernet-1/10
# Author: Mau
# check more in https://github.com/cloud-native-everything/srlinux-ansible-lab
# June 2021
#
#
- hosts: baremetals
  gather_facts: no
  remote_user: root


  pre_tasks:
    - include_vars: "/srl-lab/cfg/{{ cfg_option }}/global_vars.yml" 

  tasks:

    - name: Get management BRIDGE for the recently created leaf/spine instances
      shell: brctl show | grep 'br-' | grep 'veth' | awk '{print $1}'
      register: mgmt_br
      changed_when: False

    - name: Check management BRIDGE
      debug:
        msg: "bridge is: {{ mgmt_br.stdout }}"

    - name: Check if management BRIDGE exists
      fail:
        msg: "There is no management BRIDGE. Have you created the srl containerlab?"
      when: mgmt_br.stdout == ""

    - name: Store bridge in mgmt_bridge var
      set_fact:
        mgmt_bridge: "{{ mgmt_br.stdout }}"

    - name: Check management BRIDGE
      debug:
        msg: "bridge is: {{ mgmt_bridge }}"


    - include: /srl-lab/servers/kvm-domains.yml
    - include: /srl-lab/servers/veth-tcmirred-settings.yml
    - include: /srl-lab/servers/infra-services.yml 
#    - include: /srl-lab/servers/k8s-calico-setup.yml 

